<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SharedFlowBundle revision="3" name="SF-Employee-App-Target-Exception-Handling">
    <ConfigurationVersion majorVersion="4" minorVersion="0"/>
    <CreatedAt>1614541063575</CreatedAt>
    <CreatedBy>birurkarthik@gmail.com</CreatedBy>
    <Description>This shared flow handles all the errors thrown in the Target flow in Employee-App.</Description>
    <DisplayName>SF-Employee-App-Target-Exception-Handling</DisplayName>
    <LastModifiedAt>1614542869699</LastModifiedAt>
    <LastModifiedBy>birurkarthik@gmail.com</LastModifiedBy>
    <ManifestVersion>SHA-512:26cd8bb6e43a98f361051da0347a30218b5a5e76eaa89c09f06ec18a5577bb5f8c2ff3a3c08e22ea1d6b072727486bc3ba0359067e31ffa2ecfe06de37f574dc:eu-west-1</ManifestVersion>
    <Policies>
        <Policy>JS.TargetErrorHandling</Policy>
        <Policy>RF.ErrorMessage</Policy>
    </Policies>
    <Resources>
        <Resource>jsc://TargetErrorHandling.js</Resource>
    </Resources>
    <Spec></Spec>
    <subType>SharedFlow</subType>
    <SharedFlows>
        <SharedFlow>default</SharedFlow>
    </SharedFlows>
</SharedFlowBundle>
